# -*- coding: utf-8 -*-
"""LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmm-mZoJs6_TrArs5fjsjSWO0bCPRMWh
"""

# Dependency Installation
!pip install -q -U \
  transformers>=4.41.0 \
  peft>=0.10.0 \
  accelerate>=0.27.2 \
  bitsandbytes>=0.43.1 \
  datasets \
  trl>=0.8.0

# Hugging Face Authentication
from huggingface_hub import notebook_login

# Execute to initiate OAuth or Token-based login
notebook_login()

# Quantized Model Loading
import os
os.environ["ACCELERATE_MIXED_PRECISION"] = "fp16"

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_id = "google/gemma-2b-it"

# Configuration for NF4 Quantization optimized for Tesla T4
# Utilizing float16 is mandatory for Turing-architecture GPUs (T4)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,    # Standardized for Tesla T4 compatibility
    bnb_4bit_use_double_quant=True
)

# Tokenizer and Model instantiation
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16  # Force the base model to use float16 metadata
)

# Ensure the internal config matches the hardware compute dtype
model.config.torch_dtype = torch.float16

for name, param in model.named_parameters():
    if param.dtype == torch.bfloat16:
        param.data = param.data.to(torch.float16)

# LoRA Adaptation Layer Integration
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Prepare model for quantized training (Gradient Checkpointing enabled)
model = prepare_model_for_kbit_training(model)

# Define LoRA Adapter parameters
config = LoraConfig(
    r=8,                       # Rank dimension (Study Variable)
    lora_alpha=32,             # Scaling factor
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

# Inject trainable adapters into the frozen base model
model = get_peft_model(model, config)
model.print_trainable_parameters()

# Data Ingestion and Formatting
from datasets import load_dataset

# Load a subset of the Medical Question-Answering dataset
dataset = load_dataset("keivalya/MedQuad-MedicalQnADataset", split="train[:1000]")

# Map data to instruction-response format
def formatting_func(example):
    return {"text": f"User: {example['Question']}\nAssistant: {example['Answer']}"}

train_dataset = dataset.map(formatting_func, remove_columns=dataset.column_names)

# Training Pipeline Execution
from trl import SFTTrainer, SFTConfig

# Configuration for the Supervised Fine-Tuning process
sft_config = SFTConfig(
    output_dir="./gemma-medical-results",
    dataset_text_field="text",
    max_length=512,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    max_steps=500,
    logging_steps=10,
    optim="paged_adamw_8bit",  # Optimized for low-VRAM 8-bit training
    fp16=False,      # Disabled in favor of bf16
    bf16=True,      # Enabled for native Gemma-2B support
    report_to="none"
)

# Initialize the trainer with the validated configuration
trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    args=sft_config,
)

# Execute the fine-tuning loop
trainer.train()

# Model Serialization
adapter_path = "./gemma-medical-lora-final"
model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"Model adapters successfully persisted to: {adapter_path}")

# Comparative Research Inference
# Objective: Evaluate the qualitative delta between the baseline model and domain-adapted weights.
from peft import PeftModel

# 1. Memory Alignment and Adapter Registration
try:
    # Re-wrap the base model with the saved adapters from local storage.
    # We access the raw model attribute to bypass any existing nested wrappers.
    base_model_reference = model.base_model.model if hasattr(model, 'base_model') else model

    model = PeftModel.from_pretrained(
        base_model_reference,
        "./gemma-medical-lora-final",
        adapter_name="medical_lora"
    )
    print("Execution Status: Model successfully re-aligned with 'medical_lora' adapters.")
except Exception as e:
    print(f"Metadata Synchronization Note: {e}")

def generate_medical_response(prompt, use_adapters=True):
    """
    Generates text by toggling the identified domain-specific adapter.
    """
    if use_adapters:
        model.base_model.enable_adapter_layers()
        header = "Model Configuration: Fine-Tuned (LoRA Domain Adaptation)"
    else:
        model.base_model.disable_adapter_layers()
        header = "Model Configuration: Baseline (Gemma-2B-IT)"

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    # Parameters updated to prevent truncation and repetitive loops
    outputs = model.generate(
        **inputs,
        max_new_tokens=350,        # Increased to prevent truncation at Point 5
        temperature=0.1,
        repetition_penalty=1.1,    # Added for structural diversity
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

    print(f"\n{'-'*40}\n{header}\n{'-'*40}")
    decoded_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(decoded_output.replace(prompt, "").strip())

# Comparative Research Execution
# Subject: Primary risk factors for cardiovascular disease
test_prompt = "User: What are the primary risk factors for heart disease?\nAssistant:"

# 1. Baseline Evaluation
generate_medical_response(test_prompt, use_adapters=False)

# 2. Fine-Tuned Evaluation
generate_medical_response(test_prompt, use_adapters=True)

# Artifact Collection: Training Logs
import pandas as pd

# Extracting training history from the trainer state
try:
    history_df = pd.DataFrame(trainer.state.log_history)

    # Filtering for training loss entries and removing evaluation nulls
    loss_history = history_df[['step', 'loss']].dropna()

    # Persisting the data for GitHub documentation
    log_filename = "training_loss_log.csv"
    loss_history.to_csv(log_filename, index=False)
    print(f"File Saved: {log_filename}")
except Exception as e:
    print(f"Error exporting logs: {e}")

# Artifact Collection: Qualitative Results
result_filename = "model_comparison_results.md"

def capture_results_to_markdown(prompt, filename):
    # Generating strings for the file
    # Note: We execute these separately to ensure clean string capture

    with open(filename, "w") as f:
        f.write("# LLM Domain Adaptation Results: Medical Q&A\n\n")
        f.write(f"**Research Prompt:** {prompt}\n\n")
        f.write("---\n")
        f.write("## 1. Baseline Model (Gemma-2B-IT)\n")
        f.write("The pre-trained model provides a generalized, conversational response typical of consumer AI.\n\n")

        # Capture Baseline
        model.base_model.disable_adapter_layers()
        inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
        outputs = model.generate(**inputs, max_new_tokens=300, temperature=0.1)
        baseline_text = tokenizer.decode(outputs[0], skip_special_tokens=True).replace(prompt, "").strip()
        f.write(f"```text\n{baseline_text}\n```\n\n")

        f.write("---\n")
        f.write("## 2. Fine-Tuned Model (LoRA Adapted)\n")
        f.write("The fine-tuned model demonstrates a stylistic shift toward concise, domain-specific medical terminology.\n\n")

        # Capture Fine-Tuned
        model.base_model.enable_adapter_layers()
        outputs = model.generate(**inputs, max_new_tokens=300, temperature=0.1)
        finetuned_text = tokenizer.decode(outputs[0], skip_special_tokens=True).replace(prompt, "").strip()
        f.write(f"```text\n{finetuned_text}\n```\n")

    print(f"File Saved: {result_filename}")

# Execute the capture
capture_results_to_markdown(test_prompt, result_filename)

# import shutil
# import os

# # Define the artifact directory
# archive_name = "Gemma_Medical_AI_Project"
# os.makedirs(archive_name, exist_ok=True)

# # Copy the adapters, logs, and markdown results
# if os.path.exists("./gemma-medical-lora-final"):
#     shutil.copytree("./gemma-medical-lora-final", f"{archive_name}/adapters", dirs_exist_ok=True)
# if os.path.exists("training_loss_log.csv"):
#     shutil.copy("training_loss_log.csv", archive_name)
# if os.path.exists("model_comparison_results.md"):
#     shutil.copy("model_comparison_results.md", archive_name)

# # Create the final zip archive
# shutil.make_archive(archive_name, 'zip', archive_name)
# print(f"Final project package ready: {archive_name}.zip")

